[package]
name = "game_core"
version = "0.1.0"
authors = ["mao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = { version = "0.16", default-features = false }
glam = "0.12"
